// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: telemetry/v1/ingestion.proto
// Protobuf Java Version: 4.26.1

package factoryos.telemetry.v1;

public final class Ingestion {
  private Ingestion() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      Ingestion.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TelemetryPayloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:factoryos.telemetry.v1.TelemetryPayload)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * UUIDv7 of the Physical Asset emitting the data
     * </pre>
     *
     * <code>string physical_asset_id = 1 [json_name = "physicalAssetId"];</code>
     * @return The physicalAssetId.
     */
    java.lang.String getPhysicalAssetId();
    /**
     * <pre>
     * UUIDv7 of the Physical Asset emitting the data
     * </pre>
     *
     * <code>string physical_asset_id = 1 [json_name = "physicalAssetId"];</code>
     * @return The bytes for physicalAssetId.
     */
    com.google.protobuf.ByteString
        getPhysicalAssetIdBytes();

    /**
     * <pre>
     * The exact time the reading was taken at the edge (NOT cloud receive time)
     * </pre>
     *
     * <code>.google.protobuf.Timestamp edge_timestamp = 2 [json_name = "edgeTimestamp"];</code>
     * @return Whether the edgeTimestamp field is set.
     */
    boolean hasEdgeTimestamp();
    /**
     * <pre>
     * The exact time the reading was taken at the edge (NOT cloud receive time)
     * </pre>
     *
     * <code>.google.protobuf.Timestamp edge_timestamp = 2 [json_name = "edgeTimestamp"];</code>
     * @return The edgeTimestamp.
     */
    com.google.protobuf.Timestamp getEdgeTimestamp();
    /**
     * <pre>
     * The exact time the reading was taken at the edge (NOT cloud receive time)
     * </pre>
     *
     * <code>.google.protobuf.Timestamp edge_timestamp = 2 [json_name = "edgeTimestamp"];</code>
     */
    com.google.protobuf.TimestampOrBuilder getEdgeTimestampOrBuilder();

    /**
     * <pre>
     * Array of sensor readings to support batching
     * </pre>
     *
     * <code>repeated .factoryos.telemetry.v1.SensorReading readings = 3 [json_name = "readings"];</code>
     */
    java.util.List<factoryos.telemetry.v1.Ingestion.SensorReading> 
        getReadingsList();
    /**
     * <pre>
     * Array of sensor readings to support batching
     * </pre>
     *
     * <code>repeated .factoryos.telemetry.v1.SensorReading readings = 3 [json_name = "readings"];</code>
     */
    factoryos.telemetry.v1.Ingestion.SensorReading getReadings(int index);
    /**
     * <pre>
     * Array of sensor readings to support batching
     * </pre>
     *
     * <code>repeated .factoryos.telemetry.v1.SensorReading readings = 3 [json_name = "readings"];</code>
     */
    int getReadingsCount();
    /**
     * <pre>
     * Array of sensor readings to support batching
     * </pre>
     *
     * <code>repeated .factoryos.telemetry.v1.SensorReading readings = 3 [json_name = "readings"];</code>
     */
    java.util.List<? extends factoryos.telemetry.v1.Ingestion.SensorReadingOrBuilder> 
        getReadingsOrBuilderList();
    /**
     * <pre>
     * Array of sensor readings to support batching
     * </pre>
     *
     * <code>repeated .factoryos.telemetry.v1.SensorReading readings = 3 [json_name = "readings"];</code>
     */
    factoryos.telemetry.v1.Ingestion.SensorReadingOrBuilder getReadingsOrBuilder(
        int index);
  }
  /**
   * <pre>
   * The standardized payload sent from the Edge to the Cloud
   * </pre>
   *
   * Protobuf type {@code factoryos.telemetry.v1.TelemetryPayload}
   */
  public static final class TelemetryPayload extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:factoryos.telemetry.v1.TelemetryPayload)
      TelemetryPayloadOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        TelemetryPayload.class.getName());
    }
    // Use TelemetryPayload.newBuilder() to construct.
    private TelemetryPayload(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TelemetryPayload() {
      physicalAssetId_ = "";
      readings_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return factoryos.telemetry.v1.Ingestion.internal_static_factoryos_telemetry_v1_TelemetryPayload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return factoryos.telemetry.v1.Ingestion.internal_static_factoryos_telemetry_v1_TelemetryPayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              factoryos.telemetry.v1.Ingestion.TelemetryPayload.class, factoryos.telemetry.v1.Ingestion.TelemetryPayload.Builder.class);
    }

    private int bitField0_;
    public static final int PHYSICAL_ASSET_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object physicalAssetId_ = "";
    /**
     * <pre>
     * UUIDv7 of the Physical Asset emitting the data
     * </pre>
     *
     * <code>string physical_asset_id = 1 [json_name = "physicalAssetId"];</code>
     * @return The physicalAssetId.
     */
    @java.lang.Override
    public java.lang.String getPhysicalAssetId() {
      java.lang.Object ref = physicalAssetId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        physicalAssetId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * UUIDv7 of the Physical Asset emitting the data
     * </pre>
     *
     * <code>string physical_asset_id = 1 [json_name = "physicalAssetId"];</code>
     * @return The bytes for physicalAssetId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPhysicalAssetIdBytes() {
      java.lang.Object ref = physicalAssetId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        physicalAssetId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EDGE_TIMESTAMP_FIELD_NUMBER = 2;
    private com.google.protobuf.Timestamp edgeTimestamp_;
    /**
     * <pre>
     * The exact time the reading was taken at the edge (NOT cloud receive time)
     * </pre>
     *
     * <code>.google.protobuf.Timestamp edge_timestamp = 2 [json_name = "edgeTimestamp"];</code>
     * @return Whether the edgeTimestamp field is set.
     */
    @java.lang.Override
    public boolean hasEdgeTimestamp() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * The exact time the reading was taken at the edge (NOT cloud receive time)
     * </pre>
     *
     * <code>.google.protobuf.Timestamp edge_timestamp = 2 [json_name = "edgeTimestamp"];</code>
     * @return The edgeTimestamp.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getEdgeTimestamp() {
      return edgeTimestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : edgeTimestamp_;
    }
    /**
     * <pre>
     * The exact time the reading was taken at the edge (NOT cloud receive time)
     * </pre>
     *
     * <code>.google.protobuf.Timestamp edge_timestamp = 2 [json_name = "edgeTimestamp"];</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getEdgeTimestampOrBuilder() {
      return edgeTimestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : edgeTimestamp_;
    }

    public static final int READINGS_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private java.util.List<factoryos.telemetry.v1.Ingestion.SensorReading> readings_;
    /**
     * <pre>
     * Array of sensor readings to support batching
     * </pre>
     *
     * <code>repeated .factoryos.telemetry.v1.SensorReading readings = 3 [json_name = "readings"];</code>
     */
    @java.lang.Override
    public java.util.List<factoryos.telemetry.v1.Ingestion.SensorReading> getReadingsList() {
      return readings_;
    }
    /**
     * <pre>
     * Array of sensor readings to support batching
     * </pre>
     *
     * <code>repeated .factoryos.telemetry.v1.SensorReading readings = 3 [json_name = "readings"];</code>
     */
    @java.lang.Override
    public java.util.List<? extends factoryos.telemetry.v1.Ingestion.SensorReadingOrBuilder> 
        getReadingsOrBuilderList() {
      return readings_;
    }
    /**
     * <pre>
     * Array of sensor readings to support batching
     * </pre>
     *
     * <code>repeated .factoryos.telemetry.v1.SensorReading readings = 3 [json_name = "readings"];</code>
     */
    @java.lang.Override
    public int getReadingsCount() {
      return readings_.size();
    }
    /**
     * <pre>
     * Array of sensor readings to support batching
     * </pre>
     *
     * <code>repeated .factoryos.telemetry.v1.SensorReading readings = 3 [json_name = "readings"];</code>
     */
    @java.lang.Override
    public factoryos.telemetry.v1.Ingestion.SensorReading getReadings(int index) {
      return readings_.get(index);
    }
    /**
     * <pre>
     * Array of sensor readings to support batching
     * </pre>
     *
     * <code>repeated .factoryos.telemetry.v1.SensorReading readings = 3 [json_name = "readings"];</code>
     */
    @java.lang.Override
    public factoryos.telemetry.v1.Ingestion.SensorReadingOrBuilder getReadingsOrBuilder(
        int index) {
      return readings_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(physicalAssetId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, physicalAssetId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getEdgeTimestamp());
      }
      for (int i = 0; i < readings_.size(); i++) {
        output.writeMessage(3, readings_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(physicalAssetId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, physicalAssetId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getEdgeTimestamp());
      }
      for (int i = 0; i < readings_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, readings_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof factoryos.telemetry.v1.Ingestion.TelemetryPayload)) {
        return super.equals(obj);
      }
      factoryos.telemetry.v1.Ingestion.TelemetryPayload other = (factoryos.telemetry.v1.Ingestion.TelemetryPayload) obj;

      if (!getPhysicalAssetId()
          .equals(other.getPhysicalAssetId())) return false;
      if (hasEdgeTimestamp() != other.hasEdgeTimestamp()) return false;
      if (hasEdgeTimestamp()) {
        if (!getEdgeTimestamp()
            .equals(other.getEdgeTimestamp())) return false;
      }
      if (!getReadingsList()
          .equals(other.getReadingsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PHYSICAL_ASSET_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPhysicalAssetId().hashCode();
      if (hasEdgeTimestamp()) {
        hash = (37 * hash) + EDGE_TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getEdgeTimestamp().hashCode();
      }
      if (getReadingsCount() > 0) {
        hash = (37 * hash) + READINGS_FIELD_NUMBER;
        hash = (53 * hash) + getReadingsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static factoryos.telemetry.v1.Ingestion.TelemetryPayload parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static factoryos.telemetry.v1.Ingestion.TelemetryPayload parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static factoryos.telemetry.v1.Ingestion.TelemetryPayload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static factoryos.telemetry.v1.Ingestion.TelemetryPayload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static factoryos.telemetry.v1.Ingestion.TelemetryPayload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static factoryos.telemetry.v1.Ingestion.TelemetryPayload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static factoryos.telemetry.v1.Ingestion.TelemetryPayload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static factoryos.telemetry.v1.Ingestion.TelemetryPayload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static factoryos.telemetry.v1.Ingestion.TelemetryPayload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static factoryos.telemetry.v1.Ingestion.TelemetryPayload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static factoryos.telemetry.v1.Ingestion.TelemetryPayload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static factoryos.telemetry.v1.Ingestion.TelemetryPayload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(factoryos.telemetry.v1.Ingestion.TelemetryPayload prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The standardized payload sent from the Edge to the Cloud
     * </pre>
     *
     * Protobuf type {@code factoryos.telemetry.v1.TelemetryPayload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:factoryos.telemetry.v1.TelemetryPayload)
        factoryos.telemetry.v1.Ingestion.TelemetryPayloadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return factoryos.telemetry.v1.Ingestion.internal_static_factoryos_telemetry_v1_TelemetryPayload_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return factoryos.telemetry.v1.Ingestion.internal_static_factoryos_telemetry_v1_TelemetryPayload_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                factoryos.telemetry.v1.Ingestion.TelemetryPayload.class, factoryos.telemetry.v1.Ingestion.TelemetryPayload.Builder.class);
      }

      // Construct using factoryos.telemetry.v1.Ingestion.TelemetryPayload.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getEdgeTimestampFieldBuilder();
          getReadingsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        physicalAssetId_ = "";
        edgeTimestamp_ = null;
        if (edgeTimestampBuilder_ != null) {
          edgeTimestampBuilder_.dispose();
          edgeTimestampBuilder_ = null;
        }
        if (readingsBuilder_ == null) {
          readings_ = java.util.Collections.emptyList();
        } else {
          readings_ = null;
          readingsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return factoryos.telemetry.v1.Ingestion.internal_static_factoryos_telemetry_v1_TelemetryPayload_descriptor;
      }

      @java.lang.Override
      public factoryos.telemetry.v1.Ingestion.TelemetryPayload getDefaultInstanceForType() {
        return factoryos.telemetry.v1.Ingestion.TelemetryPayload.getDefaultInstance();
      }

      @java.lang.Override
      public factoryos.telemetry.v1.Ingestion.TelemetryPayload build() {
        factoryos.telemetry.v1.Ingestion.TelemetryPayload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public factoryos.telemetry.v1.Ingestion.TelemetryPayload buildPartial() {
        factoryos.telemetry.v1.Ingestion.TelemetryPayload result = new factoryos.telemetry.v1.Ingestion.TelemetryPayload(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(factoryos.telemetry.v1.Ingestion.TelemetryPayload result) {
        if (readingsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0)) {
            readings_ = java.util.Collections.unmodifiableList(readings_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.readings_ = readings_;
        } else {
          result.readings_ = readingsBuilder_.build();
        }
      }

      private void buildPartial0(factoryos.telemetry.v1.Ingestion.TelemetryPayload result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.physicalAssetId_ = physicalAssetId_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.edgeTimestamp_ = edgeTimestampBuilder_ == null
              ? edgeTimestamp_
              : edgeTimestampBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof factoryos.telemetry.v1.Ingestion.TelemetryPayload) {
          return mergeFrom((factoryos.telemetry.v1.Ingestion.TelemetryPayload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(factoryos.telemetry.v1.Ingestion.TelemetryPayload other) {
        if (other == factoryos.telemetry.v1.Ingestion.TelemetryPayload.getDefaultInstance()) return this;
        if (!other.getPhysicalAssetId().isEmpty()) {
          physicalAssetId_ = other.physicalAssetId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasEdgeTimestamp()) {
          mergeEdgeTimestamp(other.getEdgeTimestamp());
        }
        if (readingsBuilder_ == null) {
          if (!other.readings_.isEmpty()) {
            if (readings_.isEmpty()) {
              readings_ = other.readings_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureReadingsIsMutable();
              readings_.addAll(other.readings_);
            }
            onChanged();
          }
        } else {
          if (!other.readings_.isEmpty()) {
            if (readingsBuilder_.isEmpty()) {
              readingsBuilder_.dispose();
              readingsBuilder_ = null;
              readings_ = other.readings_;
              bitField0_ = (bitField0_ & ~0x00000004);
              readingsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getReadingsFieldBuilder() : null;
            } else {
              readingsBuilder_.addAllMessages(other.readings_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                physicalAssetId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getEdgeTimestampFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                factoryos.telemetry.v1.Ingestion.SensorReading m =
                    input.readMessage(
                        factoryos.telemetry.v1.Ingestion.SensorReading.parser(),
                        extensionRegistry);
                if (readingsBuilder_ == null) {
                  ensureReadingsIsMutable();
                  readings_.add(m);
                } else {
                  readingsBuilder_.addMessage(m);
                }
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object physicalAssetId_ = "";
      /**
       * <pre>
       * UUIDv7 of the Physical Asset emitting the data
       * </pre>
       *
       * <code>string physical_asset_id = 1 [json_name = "physicalAssetId"];</code>
       * @return The physicalAssetId.
       */
      public java.lang.String getPhysicalAssetId() {
        java.lang.Object ref = physicalAssetId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          physicalAssetId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * UUIDv7 of the Physical Asset emitting the data
       * </pre>
       *
       * <code>string physical_asset_id = 1 [json_name = "physicalAssetId"];</code>
       * @return The bytes for physicalAssetId.
       */
      public com.google.protobuf.ByteString
          getPhysicalAssetIdBytes() {
        java.lang.Object ref = physicalAssetId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          physicalAssetId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * UUIDv7 of the Physical Asset emitting the data
       * </pre>
       *
       * <code>string physical_asset_id = 1 [json_name = "physicalAssetId"];</code>
       * @param value The physicalAssetId to set.
       * @return This builder for chaining.
       */
      public Builder setPhysicalAssetId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        physicalAssetId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * UUIDv7 of the Physical Asset emitting the data
       * </pre>
       *
       * <code>string physical_asset_id = 1 [json_name = "physicalAssetId"];</code>
       * @return This builder for chaining.
       */
      public Builder clearPhysicalAssetId() {
        physicalAssetId_ = getDefaultInstance().getPhysicalAssetId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * UUIDv7 of the Physical Asset emitting the data
       * </pre>
       *
       * <code>string physical_asset_id = 1 [json_name = "physicalAssetId"];</code>
       * @param value The bytes for physicalAssetId to set.
       * @return This builder for chaining.
       */
      public Builder setPhysicalAssetIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        physicalAssetId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp edgeTimestamp_;
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> edgeTimestampBuilder_;
      /**
       * <pre>
       * The exact time the reading was taken at the edge (NOT cloud receive time)
       * </pre>
       *
       * <code>.google.protobuf.Timestamp edge_timestamp = 2 [json_name = "edgeTimestamp"];</code>
       * @return Whether the edgeTimestamp field is set.
       */
      public boolean hasEdgeTimestamp() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * The exact time the reading was taken at the edge (NOT cloud receive time)
       * </pre>
       *
       * <code>.google.protobuf.Timestamp edge_timestamp = 2 [json_name = "edgeTimestamp"];</code>
       * @return The edgeTimestamp.
       */
      public com.google.protobuf.Timestamp getEdgeTimestamp() {
        if (edgeTimestampBuilder_ == null) {
          return edgeTimestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : edgeTimestamp_;
        } else {
          return edgeTimestampBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * The exact time the reading was taken at the edge (NOT cloud receive time)
       * </pre>
       *
       * <code>.google.protobuf.Timestamp edge_timestamp = 2 [json_name = "edgeTimestamp"];</code>
       */
      public Builder setEdgeTimestamp(com.google.protobuf.Timestamp value) {
        if (edgeTimestampBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          edgeTimestamp_ = value;
        } else {
          edgeTimestampBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The exact time the reading was taken at the edge (NOT cloud receive time)
       * </pre>
       *
       * <code>.google.protobuf.Timestamp edge_timestamp = 2 [json_name = "edgeTimestamp"];</code>
       */
      public Builder setEdgeTimestamp(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (edgeTimestampBuilder_ == null) {
          edgeTimestamp_ = builderForValue.build();
        } else {
          edgeTimestampBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The exact time the reading was taken at the edge (NOT cloud receive time)
       * </pre>
       *
       * <code>.google.protobuf.Timestamp edge_timestamp = 2 [json_name = "edgeTimestamp"];</code>
       */
      public Builder mergeEdgeTimestamp(com.google.protobuf.Timestamp value) {
        if (edgeTimestampBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            edgeTimestamp_ != null &&
            edgeTimestamp_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getEdgeTimestampBuilder().mergeFrom(value);
          } else {
            edgeTimestamp_ = value;
          }
        } else {
          edgeTimestampBuilder_.mergeFrom(value);
        }
        if (edgeTimestamp_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * The exact time the reading was taken at the edge (NOT cloud receive time)
       * </pre>
       *
       * <code>.google.protobuf.Timestamp edge_timestamp = 2 [json_name = "edgeTimestamp"];</code>
       */
      public Builder clearEdgeTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        edgeTimestamp_ = null;
        if (edgeTimestampBuilder_ != null) {
          edgeTimestampBuilder_.dispose();
          edgeTimestampBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The exact time the reading was taken at the edge (NOT cloud receive time)
       * </pre>
       *
       * <code>.google.protobuf.Timestamp edge_timestamp = 2 [json_name = "edgeTimestamp"];</code>
       */
      public com.google.protobuf.Timestamp.Builder getEdgeTimestampBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getEdgeTimestampFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * The exact time the reading was taken at the edge (NOT cloud receive time)
       * </pre>
       *
       * <code>.google.protobuf.Timestamp edge_timestamp = 2 [json_name = "edgeTimestamp"];</code>
       */
      public com.google.protobuf.TimestampOrBuilder getEdgeTimestampOrBuilder() {
        if (edgeTimestampBuilder_ != null) {
          return edgeTimestampBuilder_.getMessageOrBuilder();
        } else {
          return edgeTimestamp_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : edgeTimestamp_;
        }
      }
      /**
       * <pre>
       * The exact time the reading was taken at the edge (NOT cloud receive time)
       * </pre>
       *
       * <code>.google.protobuf.Timestamp edge_timestamp = 2 [json_name = "edgeTimestamp"];</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getEdgeTimestampFieldBuilder() {
        if (edgeTimestampBuilder_ == null) {
          edgeTimestampBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getEdgeTimestamp(),
                  getParentForChildren(),
                  isClean());
          edgeTimestamp_ = null;
        }
        return edgeTimestampBuilder_;
      }

      private java.util.List<factoryos.telemetry.v1.Ingestion.SensorReading> readings_ =
        java.util.Collections.emptyList();
      private void ensureReadingsIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          readings_ = new java.util.ArrayList<factoryos.telemetry.v1.Ingestion.SensorReading>(readings_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          factoryos.telemetry.v1.Ingestion.SensorReading, factoryos.telemetry.v1.Ingestion.SensorReading.Builder, factoryos.telemetry.v1.Ingestion.SensorReadingOrBuilder> readingsBuilder_;

      /**
       * <pre>
       * Array of sensor readings to support batching
       * </pre>
       *
       * <code>repeated .factoryos.telemetry.v1.SensorReading readings = 3 [json_name = "readings"];</code>
       */
      public java.util.List<factoryos.telemetry.v1.Ingestion.SensorReading> getReadingsList() {
        if (readingsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(readings_);
        } else {
          return readingsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * Array of sensor readings to support batching
       * </pre>
       *
       * <code>repeated .factoryos.telemetry.v1.SensorReading readings = 3 [json_name = "readings"];</code>
       */
      public int getReadingsCount() {
        if (readingsBuilder_ == null) {
          return readings_.size();
        } else {
          return readingsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * Array of sensor readings to support batching
       * </pre>
       *
       * <code>repeated .factoryos.telemetry.v1.SensorReading readings = 3 [json_name = "readings"];</code>
       */
      public factoryos.telemetry.v1.Ingestion.SensorReading getReadings(int index) {
        if (readingsBuilder_ == null) {
          return readings_.get(index);
        } else {
          return readingsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * Array of sensor readings to support batching
       * </pre>
       *
       * <code>repeated .factoryos.telemetry.v1.SensorReading readings = 3 [json_name = "readings"];</code>
       */
      public Builder setReadings(
          int index, factoryos.telemetry.v1.Ingestion.SensorReading value) {
        if (readingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReadingsIsMutable();
          readings_.set(index, value);
          onChanged();
        } else {
          readingsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * Array of sensor readings to support batching
       * </pre>
       *
       * <code>repeated .factoryos.telemetry.v1.SensorReading readings = 3 [json_name = "readings"];</code>
       */
      public Builder setReadings(
          int index, factoryos.telemetry.v1.Ingestion.SensorReading.Builder builderForValue) {
        if (readingsBuilder_ == null) {
          ensureReadingsIsMutable();
          readings_.set(index, builderForValue.build());
          onChanged();
        } else {
          readingsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Array of sensor readings to support batching
       * </pre>
       *
       * <code>repeated .factoryos.telemetry.v1.SensorReading readings = 3 [json_name = "readings"];</code>
       */
      public Builder addReadings(factoryos.telemetry.v1.Ingestion.SensorReading value) {
        if (readingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReadingsIsMutable();
          readings_.add(value);
          onChanged();
        } else {
          readingsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * Array of sensor readings to support batching
       * </pre>
       *
       * <code>repeated .factoryos.telemetry.v1.SensorReading readings = 3 [json_name = "readings"];</code>
       */
      public Builder addReadings(
          int index, factoryos.telemetry.v1.Ingestion.SensorReading value) {
        if (readingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReadingsIsMutable();
          readings_.add(index, value);
          onChanged();
        } else {
          readingsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * Array of sensor readings to support batching
       * </pre>
       *
       * <code>repeated .factoryos.telemetry.v1.SensorReading readings = 3 [json_name = "readings"];</code>
       */
      public Builder addReadings(
          factoryos.telemetry.v1.Ingestion.SensorReading.Builder builderForValue) {
        if (readingsBuilder_ == null) {
          ensureReadingsIsMutable();
          readings_.add(builderForValue.build());
          onChanged();
        } else {
          readingsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Array of sensor readings to support batching
       * </pre>
       *
       * <code>repeated .factoryos.telemetry.v1.SensorReading readings = 3 [json_name = "readings"];</code>
       */
      public Builder addReadings(
          int index, factoryos.telemetry.v1.Ingestion.SensorReading.Builder builderForValue) {
        if (readingsBuilder_ == null) {
          ensureReadingsIsMutable();
          readings_.add(index, builderForValue.build());
          onChanged();
        } else {
          readingsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Array of sensor readings to support batching
       * </pre>
       *
       * <code>repeated .factoryos.telemetry.v1.SensorReading readings = 3 [json_name = "readings"];</code>
       */
      public Builder addAllReadings(
          java.lang.Iterable<? extends factoryos.telemetry.v1.Ingestion.SensorReading> values) {
        if (readingsBuilder_ == null) {
          ensureReadingsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, readings_);
          onChanged();
        } else {
          readingsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * Array of sensor readings to support batching
       * </pre>
       *
       * <code>repeated .factoryos.telemetry.v1.SensorReading readings = 3 [json_name = "readings"];</code>
       */
      public Builder clearReadings() {
        if (readingsBuilder_ == null) {
          readings_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          readingsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * Array of sensor readings to support batching
       * </pre>
       *
       * <code>repeated .factoryos.telemetry.v1.SensorReading readings = 3 [json_name = "readings"];</code>
       */
      public Builder removeReadings(int index) {
        if (readingsBuilder_ == null) {
          ensureReadingsIsMutable();
          readings_.remove(index);
          onChanged();
        } else {
          readingsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * Array of sensor readings to support batching
       * </pre>
       *
       * <code>repeated .factoryos.telemetry.v1.SensorReading readings = 3 [json_name = "readings"];</code>
       */
      public factoryos.telemetry.v1.Ingestion.SensorReading.Builder getReadingsBuilder(
          int index) {
        return getReadingsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * Array of sensor readings to support batching
       * </pre>
       *
       * <code>repeated .factoryos.telemetry.v1.SensorReading readings = 3 [json_name = "readings"];</code>
       */
      public factoryos.telemetry.v1.Ingestion.SensorReadingOrBuilder getReadingsOrBuilder(
          int index) {
        if (readingsBuilder_ == null) {
          return readings_.get(index);  } else {
          return readingsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * Array of sensor readings to support batching
       * </pre>
       *
       * <code>repeated .factoryos.telemetry.v1.SensorReading readings = 3 [json_name = "readings"];</code>
       */
      public java.util.List<? extends factoryos.telemetry.v1.Ingestion.SensorReadingOrBuilder> 
           getReadingsOrBuilderList() {
        if (readingsBuilder_ != null) {
          return readingsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(readings_);
        }
      }
      /**
       * <pre>
       * Array of sensor readings to support batching
       * </pre>
       *
       * <code>repeated .factoryos.telemetry.v1.SensorReading readings = 3 [json_name = "readings"];</code>
       */
      public factoryos.telemetry.v1.Ingestion.SensorReading.Builder addReadingsBuilder() {
        return getReadingsFieldBuilder().addBuilder(
            factoryos.telemetry.v1.Ingestion.SensorReading.getDefaultInstance());
      }
      /**
       * <pre>
       * Array of sensor readings to support batching
       * </pre>
       *
       * <code>repeated .factoryos.telemetry.v1.SensorReading readings = 3 [json_name = "readings"];</code>
       */
      public factoryos.telemetry.v1.Ingestion.SensorReading.Builder addReadingsBuilder(
          int index) {
        return getReadingsFieldBuilder().addBuilder(
            index, factoryos.telemetry.v1.Ingestion.SensorReading.getDefaultInstance());
      }
      /**
       * <pre>
       * Array of sensor readings to support batching
       * </pre>
       *
       * <code>repeated .factoryos.telemetry.v1.SensorReading readings = 3 [json_name = "readings"];</code>
       */
      public java.util.List<factoryos.telemetry.v1.Ingestion.SensorReading.Builder> 
           getReadingsBuilderList() {
        return getReadingsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          factoryos.telemetry.v1.Ingestion.SensorReading, factoryos.telemetry.v1.Ingestion.SensorReading.Builder, factoryos.telemetry.v1.Ingestion.SensorReadingOrBuilder> 
          getReadingsFieldBuilder() {
        if (readingsBuilder_ == null) {
          readingsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              factoryos.telemetry.v1.Ingestion.SensorReading, factoryos.telemetry.v1.Ingestion.SensorReading.Builder, factoryos.telemetry.v1.Ingestion.SensorReadingOrBuilder>(
                  readings_,
                  ((bitField0_ & 0x00000004) != 0),
                  getParentForChildren(),
                  isClean());
          readings_ = null;
        }
        return readingsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:factoryos.telemetry.v1.TelemetryPayload)
    }

    // @@protoc_insertion_point(class_scope:factoryos.telemetry.v1.TelemetryPayload)
    private static final factoryos.telemetry.v1.Ingestion.TelemetryPayload DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new factoryos.telemetry.v1.Ingestion.TelemetryPayload();
    }

    public static factoryos.telemetry.v1.Ingestion.TelemetryPayload getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TelemetryPayload>
        PARSER = new com.google.protobuf.AbstractParser<TelemetryPayload>() {
      @java.lang.Override
      public TelemetryPayload parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TelemetryPayload> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TelemetryPayload> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public factoryos.telemetry.v1.Ingestion.TelemetryPayload getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SensorReadingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:factoryos.telemetry.v1.SensorReading)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * E.g., "temperature_celsius", "spindle_vibration", "cycle_count"
     * </pre>
     *
     * <code>string metric_name = 1 [json_name = "metricName"];</code>
     * @return The metricName.
     */
    java.lang.String getMetricName();
    /**
     * <pre>
     * E.g., "temperature_celsius", "spindle_vibration", "cycle_count"
     * </pre>
     *
     * <code>string metric_name = 1 [json_name = "metricName"];</code>
     * @return The bytes for metricName.
     */
    com.google.protobuf.ByteString
        getMetricNameBytes();

    /**
     * <pre>
     * The value of the reading
     * </pre>
     *
     * <code>double value = 2 [json_name = "value"];</code>
     * @return The value.
     */
    double getValue();

    /**
     * <pre>
     * Optional: Data quality flag (e.g., "GOOD", "BAD", "UNCERTAIN")
     * </pre>
     *
     * <code>string quality = 3 [json_name = "quality"];</code>
     * @return The quality.
     */
    java.lang.String getQuality();
    /**
     * <pre>
     * Optional: Data quality flag (e.g., "GOOD", "BAD", "UNCERTAIN")
     * </pre>
     *
     * <code>string quality = 3 [json_name = "quality"];</code>
     * @return The bytes for quality.
     */
    com.google.protobuf.ByteString
        getQualityBytes();
  }
  /**
   * <pre>
   * An individual sensor reading from a machine
   * </pre>
   *
   * Protobuf type {@code factoryos.telemetry.v1.SensorReading}
   */
  public static final class SensorReading extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:factoryos.telemetry.v1.SensorReading)
      SensorReadingOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        SensorReading.class.getName());
    }
    // Use SensorReading.newBuilder() to construct.
    private SensorReading(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private SensorReading() {
      metricName_ = "";
      quality_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return factoryos.telemetry.v1.Ingestion.internal_static_factoryos_telemetry_v1_SensorReading_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return factoryos.telemetry.v1.Ingestion.internal_static_factoryos_telemetry_v1_SensorReading_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              factoryos.telemetry.v1.Ingestion.SensorReading.class, factoryos.telemetry.v1.Ingestion.SensorReading.Builder.class);
    }

    public static final int METRIC_NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object metricName_ = "";
    /**
     * <pre>
     * E.g., "temperature_celsius", "spindle_vibration", "cycle_count"
     * </pre>
     *
     * <code>string metric_name = 1 [json_name = "metricName"];</code>
     * @return The metricName.
     */
    @java.lang.Override
    public java.lang.String getMetricName() {
      java.lang.Object ref = metricName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        metricName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * E.g., "temperature_celsius", "spindle_vibration", "cycle_count"
     * </pre>
     *
     * <code>string metric_name = 1 [json_name = "metricName"];</code>
     * @return The bytes for metricName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMetricNameBytes() {
      java.lang.Object ref = metricName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        metricName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private double value_ = 0D;
    /**
     * <pre>
     * The value of the reading
     * </pre>
     *
     * <code>double value = 2 [json_name = "value"];</code>
     * @return The value.
     */
    @java.lang.Override
    public double getValue() {
      return value_;
    }

    public static final int QUALITY_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object quality_ = "";
    /**
     * <pre>
     * Optional: Data quality flag (e.g., "GOOD", "BAD", "UNCERTAIN")
     * </pre>
     *
     * <code>string quality = 3 [json_name = "quality"];</code>
     * @return The quality.
     */
    @java.lang.Override
    public java.lang.String getQuality() {
      java.lang.Object ref = quality_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        quality_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Optional: Data quality flag (e.g., "GOOD", "BAD", "UNCERTAIN")
     * </pre>
     *
     * <code>string quality = 3 [json_name = "quality"];</code>
     * @return The bytes for quality.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getQualityBytes() {
      java.lang.Object ref = quality_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        quality_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(metricName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, metricName_);
      }
      if (java.lang.Double.doubleToRawLongBits(value_) != 0) {
        output.writeDouble(2, value_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(quality_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, quality_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(metricName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, metricName_);
      }
      if (java.lang.Double.doubleToRawLongBits(value_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, value_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(quality_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, quality_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof factoryos.telemetry.v1.Ingestion.SensorReading)) {
        return super.equals(obj);
      }
      factoryos.telemetry.v1.Ingestion.SensorReading other = (factoryos.telemetry.v1.Ingestion.SensorReading) obj;

      if (!getMetricName()
          .equals(other.getMetricName())) return false;
      if (java.lang.Double.doubleToLongBits(getValue())
          != java.lang.Double.doubleToLongBits(
              other.getValue())) return false;
      if (!getQuality()
          .equals(other.getQuality())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + METRIC_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getMetricName().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getValue()));
      hash = (37 * hash) + QUALITY_FIELD_NUMBER;
      hash = (53 * hash) + getQuality().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static factoryos.telemetry.v1.Ingestion.SensorReading parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static factoryos.telemetry.v1.Ingestion.SensorReading parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static factoryos.telemetry.v1.Ingestion.SensorReading parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static factoryos.telemetry.v1.Ingestion.SensorReading parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static factoryos.telemetry.v1.Ingestion.SensorReading parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static factoryos.telemetry.v1.Ingestion.SensorReading parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static factoryos.telemetry.v1.Ingestion.SensorReading parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static factoryos.telemetry.v1.Ingestion.SensorReading parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static factoryos.telemetry.v1.Ingestion.SensorReading parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static factoryos.telemetry.v1.Ingestion.SensorReading parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static factoryos.telemetry.v1.Ingestion.SensorReading parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static factoryos.telemetry.v1.Ingestion.SensorReading parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(factoryos.telemetry.v1.Ingestion.SensorReading prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * An individual sensor reading from a machine
     * </pre>
     *
     * Protobuf type {@code factoryos.telemetry.v1.SensorReading}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:factoryos.telemetry.v1.SensorReading)
        factoryos.telemetry.v1.Ingestion.SensorReadingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return factoryos.telemetry.v1.Ingestion.internal_static_factoryos_telemetry_v1_SensorReading_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return factoryos.telemetry.v1.Ingestion.internal_static_factoryos_telemetry_v1_SensorReading_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                factoryos.telemetry.v1.Ingestion.SensorReading.class, factoryos.telemetry.v1.Ingestion.SensorReading.Builder.class);
      }

      // Construct using factoryos.telemetry.v1.Ingestion.SensorReading.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        metricName_ = "";
        value_ = 0D;
        quality_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return factoryos.telemetry.v1.Ingestion.internal_static_factoryos_telemetry_v1_SensorReading_descriptor;
      }

      @java.lang.Override
      public factoryos.telemetry.v1.Ingestion.SensorReading getDefaultInstanceForType() {
        return factoryos.telemetry.v1.Ingestion.SensorReading.getDefaultInstance();
      }

      @java.lang.Override
      public factoryos.telemetry.v1.Ingestion.SensorReading build() {
        factoryos.telemetry.v1.Ingestion.SensorReading result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public factoryos.telemetry.v1.Ingestion.SensorReading buildPartial() {
        factoryos.telemetry.v1.Ingestion.SensorReading result = new factoryos.telemetry.v1.Ingestion.SensorReading(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(factoryos.telemetry.v1.Ingestion.SensorReading result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.metricName_ = metricName_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.value_ = value_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.quality_ = quality_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof factoryos.telemetry.v1.Ingestion.SensorReading) {
          return mergeFrom((factoryos.telemetry.v1.Ingestion.SensorReading)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(factoryos.telemetry.v1.Ingestion.SensorReading other) {
        if (other == factoryos.telemetry.v1.Ingestion.SensorReading.getDefaultInstance()) return this;
        if (!other.getMetricName().isEmpty()) {
          metricName_ = other.metricName_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getValue() != 0D) {
          setValue(other.getValue());
        }
        if (!other.getQuality().isEmpty()) {
          quality_ = other.quality_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                metricName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 17: {
                value_ = input.readDouble();
                bitField0_ |= 0x00000002;
                break;
              } // case 17
              case 26: {
                quality_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object metricName_ = "";
      /**
       * <pre>
       * E.g., "temperature_celsius", "spindle_vibration", "cycle_count"
       * </pre>
       *
       * <code>string metric_name = 1 [json_name = "metricName"];</code>
       * @return The metricName.
       */
      public java.lang.String getMetricName() {
        java.lang.Object ref = metricName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          metricName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * E.g., "temperature_celsius", "spindle_vibration", "cycle_count"
       * </pre>
       *
       * <code>string metric_name = 1 [json_name = "metricName"];</code>
       * @return The bytes for metricName.
       */
      public com.google.protobuf.ByteString
          getMetricNameBytes() {
        java.lang.Object ref = metricName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          metricName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * E.g., "temperature_celsius", "spindle_vibration", "cycle_count"
       * </pre>
       *
       * <code>string metric_name = 1 [json_name = "metricName"];</code>
       * @param value The metricName to set.
       * @return This builder for chaining.
       */
      public Builder setMetricName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        metricName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * E.g., "temperature_celsius", "spindle_vibration", "cycle_count"
       * </pre>
       *
       * <code>string metric_name = 1 [json_name = "metricName"];</code>
       * @return This builder for chaining.
       */
      public Builder clearMetricName() {
        metricName_ = getDefaultInstance().getMetricName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * E.g., "temperature_celsius", "spindle_vibration", "cycle_count"
       * </pre>
       *
       * <code>string metric_name = 1 [json_name = "metricName"];</code>
       * @param value The bytes for metricName to set.
       * @return This builder for chaining.
       */
      public Builder setMetricNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        metricName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private double value_ ;
      /**
       * <pre>
       * The value of the reading
       * </pre>
       *
       * <code>double value = 2 [json_name = "value"];</code>
       * @return The value.
       */
      @java.lang.Override
      public double getValue() {
        return value_;
      }
      /**
       * <pre>
       * The value of the reading
       * </pre>
       *
       * <code>double value = 2 [json_name = "value"];</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(double value) {

        value_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The value of the reading
       * </pre>
       *
       * <code>double value = 2 [json_name = "value"];</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object quality_ = "";
      /**
       * <pre>
       * Optional: Data quality flag (e.g., "GOOD", "BAD", "UNCERTAIN")
       * </pre>
       *
       * <code>string quality = 3 [json_name = "quality"];</code>
       * @return The quality.
       */
      public java.lang.String getQuality() {
        java.lang.Object ref = quality_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          quality_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Optional: Data quality flag (e.g., "GOOD", "BAD", "UNCERTAIN")
       * </pre>
       *
       * <code>string quality = 3 [json_name = "quality"];</code>
       * @return The bytes for quality.
       */
      public com.google.protobuf.ByteString
          getQualityBytes() {
        java.lang.Object ref = quality_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          quality_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Optional: Data quality flag (e.g., "GOOD", "BAD", "UNCERTAIN")
       * </pre>
       *
       * <code>string quality = 3 [json_name = "quality"];</code>
       * @param value The quality to set.
       * @return This builder for chaining.
       */
      public Builder setQuality(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        quality_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Optional: Data quality flag (e.g., "GOOD", "BAD", "UNCERTAIN")
       * </pre>
       *
       * <code>string quality = 3 [json_name = "quality"];</code>
       * @return This builder for chaining.
       */
      public Builder clearQuality() {
        quality_ = getDefaultInstance().getQuality();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Optional: Data quality flag (e.g., "GOOD", "BAD", "UNCERTAIN")
       * </pre>
       *
       * <code>string quality = 3 [json_name = "quality"];</code>
       * @param value The bytes for quality to set.
       * @return This builder for chaining.
       */
      public Builder setQualityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        quality_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:factoryos.telemetry.v1.SensorReading)
    }

    // @@protoc_insertion_point(class_scope:factoryos.telemetry.v1.SensorReading)
    private static final factoryos.telemetry.v1.Ingestion.SensorReading DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new factoryos.telemetry.v1.Ingestion.SensorReading();
    }

    public static factoryos.telemetry.v1.Ingestion.SensorReading getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SensorReading>
        PARSER = new com.google.protobuf.AbstractParser<SensorReading>() {
      @java.lang.Override
      public SensorReading parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SensorReading> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SensorReading> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public factoryos.telemetry.v1.Ingestion.SensorReading getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_factoryos_telemetry_v1_TelemetryPayload_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_factoryos_telemetry_v1_TelemetryPayload_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_factoryos_telemetry_v1_SensorReading_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_factoryos_telemetry_v1_SensorReading_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034telemetry/v1/ingestion.proto\022\026factoryo" +
      "s.telemetry.v1\032\037google/protobuf/timestam" +
      "p.proto\"\304\001\n\020TelemetryPayload\022*\n\021physical" +
      "_asset_id\030\001 \001(\tR\017physicalAssetId\022A\n\016edge" +
      "_timestamp\030\002 \001(\0132\032.google.protobuf.Times" +
      "tampR\redgeTimestamp\022A\n\010readings\030\003 \003(\0132%." +
      "factoryos.telemetry.v1.SensorReadingR\010re" +
      "adings\"`\n\rSensorReading\022\037\n\013metric_name\030\001" +
      " \001(\tR\nmetricName\022\024\n\005value\030\002 \001(\001R\005value\022\030" +
      "\n\007quality\030\003 \001(\tR\007qualityB<Z:github.com/i" +
      "amraydoan/factoryos/api/contracts/teleme" +
      "try/v1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_factoryos_telemetry_v1_TelemetryPayload_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_factoryos_telemetry_v1_TelemetryPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_factoryos_telemetry_v1_TelemetryPayload_descriptor,
        new java.lang.String[] { "PhysicalAssetId", "EdgeTimestamp", "Readings", });
    internal_static_factoryos_telemetry_v1_SensorReading_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_factoryos_telemetry_v1_SensorReading_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_factoryos_telemetry_v1_SensorReading_descriptor,
        new java.lang.String[] { "MetricName", "Value", "Quality", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
